In [4]:
import tensorflow as tf
import numpy as np

In [2]:
#shape : length of axis
#rank : no of axis
#size : total no of items in tensor or matrix


## Rank Tensor


In [8]:
#rank 0 tensor  = scalar


rank_0_tensor = tf.constant(15)


print(tf.rank(rank_0_tensor))
print( "Rank of the tensor is " , tf.rank(rank_0_tensor).numpy())

tf.Tensor(0, shape=(), dtype=int32)
Rank of the tensor is  0


In [25]:
# Rank 1 tensor = 1-d array
rank_1_tensor = tf.constant([15 , 12 ])

print(tf.rank(rank_1_tensor))
print( "Rank of the tensor is " , tf.rank(rank_1_tensor).numpy())


print(" Dimension of array " , (rank_1_tensor.numpy()).ndim )


tf.Tensor(1, shape=(), dtype=int32)
Rank of the tensor is  1
 Dimension of array  1


## rank 2 tensor   = double [[

In [21]:
#rank 2 tesor
rank_2_tensor = tf.constant([

                             [12 , 13 ] ,
                             [14 , 15 ]

                            ])



In [27]:
print(tf.rank(rank_2_tensor))

print()

print( f"This is {tf.rank(rank_2_tensor).numpy()}-D tensor " )

tf.Tensor(2, shape=(), dtype=int32)

This is 2-D tensor 


In [33]:
#more exmples  of 2-d tensor
a1 = tf.constant([[2 ]])
print(f"{a1.numpy()} is {tf.rank(a1).numpy()}- D tensor ")



[[2]] is 2- D tensor 


## Rank 3 tensor

In [38]:
c = tf.constant([[

     [12 , 13  ] ,
     [14 , 15 ]

     ]])

#note that the shape() means this is bad example of tensor
tf.rank(c)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [58]:
d = tf.constant([

                 [

                 [2 , 3 , 6  , 4 ] ,
                 [6  , 4 , 8 , 4  ]

                 ],


                 [[9 , 10 , 11 ,  4 ] ,
                 [12 , 13 , 14   , 4 ]],


                [[4 , 5 , 6  , 4   ] ,
                 [7 , 8 , 9  , 4 ]]


                 ])

In [59]:
print(d)
print()
print()

print(f"The given tensor is  {tf.rank(d).numpy()} -d tensor and \n {d.numpy().ndim} -d array of shape {d.numpy().shape}  " )
print()


tf.Tensor(
[[[ 2  3  6  4]
  [ 6  4  8  4]]

 [[ 9 10 11  4]
  [12 13 14  4]]

 [[ 4  5  6  4]
  [ 7  8  9  4]]], shape=(3, 2, 4), dtype=int32)


The given tensor is  3 -d tensor and 
 3 -d array of shape (3, 2, 4)  



In [55]:
d.numpy().ndim

3

In [61]:
#also rank 3 tensor
c1  = tf.constant([[[1]]])
tf.rank(c1).numpy()

3

## Basic math matical operation

In [62]:
a = 12
b = 16

In [63]:
tf.add(a , b)

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [64]:
tf.subtract(a , b )

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [65]:
tf.multiply(a ,b )

<tf.Tensor: shape=(), dtype=int32, numpy=192>

In [66]:
tf.divide(a , b )

<tf.Tensor: shape=(), dtype=float64, numpy=0.75>

In [82]:
#or  we can make this simple as
a = tf.constant([12 , 13 ] )
b = tf.constant([16  , 13 ] )

In [84]:
print(a + b)
print(a * b) #note this is mul not matrixx multiplication  >- 12 * 16 , 13 - 13
print(a - b )
print(a / b)

tf.Tensor([28 26], shape=(2,), dtype=int32)
tf.Tensor([192 169], shape=(2,), dtype=int32)
tf.Tensor([-4  0], shape=(2,), dtype=int32)
tf.Tensor([0.75 1.  ], shape=(2,), dtype=float64)


## Matrix Multiplication

In [96]:
# I AM GOING TO USE 2*3 MATRIX HERE  and 3*2 matrix
mat1 = tf.constant([[1 , 2 , 3]  , [4 , 5 , 6]])
mat2 = tf.constant([[2 , 4 ] , [5  , 7  ] , [ 8 , 9 ]])
print(mat1.shape)
print(mat2.shape)

(2, 3)
(3, 2)


In [97]:
#matrix muultiplication
tf.matmul(mat1 , mat2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  45],
       [ 81, 105]], dtype=int32)>

In [99]:
#or you can also use "@"
mat1 @ mat2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  45],
       [ 81, 105]], dtype=int32)>

## MAX / MIN  VALUES

## Reduce

###  *tf*.reduce refers to a set of functions that perform reduction operations on tensors. A reduction operation reduces the dimensions of a tensor by aggregating its values along one or more axes.


#### tf.reduce functions take two main arguments: the input tensor and the axis or axes

######  aggregating -process of combining multiple values into a single value based on a specified operation

In [129]:
print(tf.reduce_max(mat1).numpy())
print(tf.reduce_min(mat1).numpy())


6
1


In [130]:
print(tf.reduce_min(mat2).numpy())
print(tf.reduce_max(mat2).numpy())

2
9


In [131]:
# same as numpy
print(np.max(mat1))
print(np.min(mat1))

print()
print(np.max(mat2))
print(np.min(mat2))



6
1

9
2


### For Axis

In [132]:
print(mat1.numpy())

[[1 2 3]
 [4 5 6]]


In [133]:
tf.reduce_sum(mat1).numpy()  # 1 + 2 + 3 + 4 + 5 + 6

21

In [137]:
tf.reduce_max(mat1 , axis = 0 ).numpy() # max according to columns -> 1, 4 = 4 max  ;  2 , 5 -> = 5  max so on


array([4, 5, 6], dtype=int32)

In [135]:
tf.reduce_min(mat2 , axis = 1 ).numpy()

array([2, 5, 8], dtype=int32)

In [136]:
tf.reduce_sum(mat1 , axis = 0 ).numpy()

array([5, 7, 9], dtype=int32)

## get index for largest values

In [141]:
tf.argmax(mat1).numpy()

array([1, 1, 1])

In [152]:
tf.argmax(mat1  , axis = 1  ).numpy()


array([2, 2])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [155]:
mat1[ 1 , 2 ]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## Total elements in a Tensor

In [157]:
mat1.shape

TensorShape([2, 3])

In [159]:
2*3  # is the total no of elements

6

In [161]:
tf.size(mat1).numpy()

6

In [164]:
a = tf.zeros([4 , 5 , 6 , 7 ])

In [163]:
4 * 5 * 6 * 7

840

In [165]:
tf.size(a).numpy()

840